[project]
name = "langchain-agentic-prompt-engineering"
version = "0.1.0"
description = "..."
readme = "README.md"
requires-python = ">=3.12.7"
dependencies = [
    "ipykernel>=6.29.5",
    "langchain-openai>=0.3.3",
    "langchain>=0.3.17",
]
